/*
 * Bryce Dingwall
 * March 22, 2017
 * Birthday program that asks for a name and date and outputs data to creen
 */

/**
 *
 * @author brdin1728
 */
public class birthdayProgram extends javax.swing.JFrame {

    /**
     * Creates new form birthdayProgram
     */
    public birthdayProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        titleBar = new javax.swing.JLabel();
        inputField1 = new javax.swing.JTextField();
        inputField2 = new javax.swing.JTextField();
        nameBar = new javax.swing.JLabel();
        dateBar = new javax.swing.JLabel();
        inputOption = new javax.swing.JButton();
        outputBar = new javax.swing.JLabel();
        datCake = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        fileItem = new javax.swing.JMenu();
        exitFunction = new javax.swing.JMenuItem();
        printFunction = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenu();
        jeffGoldblum = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);

        panel.setBackground(new java.awt.Color(153, 204, 255));
        panel.setForeground(new java.awt.Color(23, 123, 34));

        titleBar.setFont(new java.awt.Font("Three Arrows", 0, 36)); // NOI18N
        titleBar.setForeground(new java.awt.Color(0, 0, 204));
        titleBar.setText("Birthday Time!");

        inputField1.setBackground(new java.awt.Color(204, 255, 153));
        inputField1.setFont(new java.awt.Font("Batang", 0, 12)); // NOI18N
        inputField1.setForeground(new java.awt.Color(255, 0, 51));
        inputField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputField1ActionPerformed(evt);
            }
        });

        inputField2.setBackground(new java.awt.Color(255, 153, 153));
        inputField2.setFont(new java.awt.Font("SerifaDEELig", 0, 12)); // NOI18N
        inputField2.setForeground(new java.awt.Color(153, 255, 102));

        nameBar.setFont(new java.awt.Font("LucidaSanTCY", 1, 12)); // NOI18N
        nameBar.setForeground(new java.awt.Color(204, 0, 204));
        nameBar.setText("Your name:");

        dateBar.setFont(new java.awt.Font("LucidaSanTCY", 1, 11)); // NOI18N
        dateBar.setForeground(new java.awt.Color(255, 0, 0));
        dateBar.setText("Your birth date:");

        inputOption.setBackground(new java.awt.Color(51, 255, 0));
        inputOption.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 14)); // NOI18N
        inputOption.setForeground(new java.awt.Color(255, 102, 0));
        inputOption.setText("PARTY TIME");
        inputOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOptionActionPerformed(evt);
            }
        });

        outputBar.setFont(new java.awt.Font("Algerian", 2, 14)); // NOI18N
        outputBar.setForeground(new java.awt.Color(255, 255, 0));
        outputBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        datCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthday-cake-slice-clipart-birthdaycake.gif"))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(titleBar)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameBar)
                    .addComponent(dateBar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputField2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(inputField1))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(outputBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(inputOption, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(datCake)))
                .addGap(19, 19, 19))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleBar)
                .addGap(40, 40, 40)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameBar)
                    .addComponent(inputField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateBar))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(inputOption, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(datCake)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(outputBar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fileItem.setText("File");

        exitFunction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        exitFunction.setText("Exit");
        exitFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFunctionActionPerformed(evt);
            }
        });
        fileItem.add(exitFunction);

        printFunction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        printFunction.setText("Print");
        fileItem.add(printFunction);

        MenuBar.add(fileItem);

        exitItem.setText("Edit");

        jeffGoldblum.setText("Jeff Goldblum");
        jeffGoldblum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeffGoldblumActionPerformed(evt);
            }
        });
        exitItem.add(jeffGoldblum);

        MenuBar.add(exitItem);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputField1ActionPerformed

    private void jeffGoldblumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeffGoldblumActionPerformed
        System.out.println("What have you done?");
    }//GEN-LAST:event_jeffGoldblumActionPerformed

    private void inputOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOptionActionPerformed
        String name = "";
        String date = "";
        date = inputField2.getText();
        name = inputField1.getText();
        outputBar.setText("" + name + "'s birthday is on " + date);
    }//GEN-LAST:event_inputOptionActionPerformed

    private void exitFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFunctionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitFunctionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(birthdayProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(birthdayProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(birthdayProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(birthdayProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new birthdayProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel datCake;
    private javax.swing.JLabel dateBar;
    private javax.swing.JMenuItem exitFunction;
    private javax.swing.JMenu exitItem;
    private javax.swing.JMenu fileItem;
    private javax.swing.JTextField inputField1;
    private javax.swing.JTextField inputField2;
    private javax.swing.JButton inputOption;
    private javax.swing.JMenuItem jeffGoldblum;
    private javax.swing.JLabel nameBar;
    private javax.swing.JLabel outputBar;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem printFunction;
    private javax.swing.JLabel titleBar;
    // End of variables declaration//GEN-END:variables
}
